### PR TITLE
Improve card and add dependencies

### PR DESCRIPTION
**Pull request by emmalearnscode**
I added extra information to the card and changed the styling slightly.

This PR fixes issue 4, 6 and 12.

Let me know if there's anything you want changing.

### CODE REVIEW

**Comment by emmalearnscode** [comment]
Are you able to see why the checks are failing?

**Comment by arvind0598** [comment]
Yep. The reason it fails is because of the lint checks. You can run `npm run lint` locally to see those errors.

You can also just run `npm run build` locally to see the issues. They should ideally be the same as what Vercel is complaining about.

**Comment by emmalearnscode** [comment]
Ok, I'll see if I can work out how to fix it, then update here when it's ready for review

**Comment by arvind0598** [comment]
Most of those issues seem to be auto fixable, so an `npm run lint:fix` should take care of that for you.

You can use the ESLint plugin for VS Code for some good contextual help when you hover on the bits that are erroring out.

**Comment by emmalearnscode** [comment]
Thanks for the tip! That fixed it :)

**Comment by arvind0598** [comment]
This looks good to me, thanks @emmalearnscode. Just as an FYI though, please do try to stick to the commit message format outlined in the contributing guide.

**Comment by emmalearnscode** [comment]
Thanks for the tip, I was working on a couple of different repos at the same time and must’ve got mixed up with how to write commit messages. I will definitely check more carefully from now on.

**Pull request merged**
